### ISSUE TITLE
Ensure game viewport doesn't change size/ratio when resizing or playing web export

### ISSUE THREAD

**Issue by Succubuster** [Succubuster/TD2D#1]
Contain the scene within a fixed viewport so window size doesn't matter
- Gives the game its own pre sized window and maintains size consistency

**Comment by flamechips** [comment]
Originally was going to use a Viewport node to solve this, but honestly just setting `Project Settings` -> `Stretch Mode` to 'viewport' does the same thing, so i'm going with that
