### ISSUE TITLE
Update project to Godot 4.2

### ISSUE THREAD

**Issue by flamechips** [Succubuster/TD2D#14]
Godot 4.2 introduces navmesh baking for 2D which would solve a lot of the issues we've already run into with this project

**Comment by Succubuster** [comment]
"we uh
we might wanna try using Godot 4.2 beta
namely because they finally added navmesh baking for 2D
also sounds like tilemaps got some love"

    a friend, a pro, a programming god

**Comment by flamechips** [comment]
Godot's project file doesn't actually differentiate between beta versions, just the release version itself (`4.2`) & since it's in feature-freeze anyways, we're probably good to just stay up-to-date as the betas come out, and then eventually 4.2 stable... likely a few weeks from now
